#  $Id$
#
#  plex86: run multiple x86 operating systems concurrently
#  Copyright (C) 1999-2003  Kevin P. Lawton

.PHONY: all clean dist-clean

include ../Rules.make


all:

clean:
	@/bin/rm -f *.o *.s

dist-clean: clean
