#!/bin/bash

if [ $# != 1 ] ; then
  exit 1
fi


# Setup network interface parameters for tun/tap device,
# usually named tun0, tun1, ...  My /etc/hosts entry looks like:
#
# 192.168.10.1    host-vmnet

/sbin/ifconfig $1 hw ether FE:FD:00:00:00:01 host-vmnet
if [ $? != 0 ] ; then
  exit 1
fi

exit 0
